site_name: graphsrv
site_url: https://github.com/20c/graphsrv

theme: readthedocs

pages:
  - Home: index.md
  - Getting started: start.md
  - Customization: custom.md
  - Templates: template.md
  - Graphs: graphs.md
  - Embed: embed.md

markdown_extensions:
  - markdown_include.include
